---
- name: Create sickrage folder
  file: path={{ item }} state=directory
  with_items:
    - "{{ sickrage_path }}"

- template:
    src: config.ini.j2
    dest: /opt/sickrage/config.ini
    owner: user
    backup: no

- name: Create Sickrage container
  docker_container:
    name: sickrage
    image: linuxserver/sickrage
    network_mode: host
    restart_policy: always
    state: started
    pull: yes
    volumes:
       - /opt/sickrage:/config
       - /mnt/data/downloads/tv:/downloads
       - /mnt/data/tv:/tv
    exposed_ports:
      - 8081
    published_ports:
      - "8081:8081"
    env:
      TZ: America/Toronto # offset = -05:00 / DST -04:00
      PUID: 1000
      PGID: 1000

- pause:
    seconds: 5

- uri:
    url: "http://{{ uTower_user_user }}:{{ uTower_user_pass }}@{{ host_ip }}:8081"
  register: login

- pushbullet:
    api_key: "{{ pushbullet_api }}"
    title: Sickrage web service is UP!
    device: Chrome
    body: "http://{{ host_ip }}:8081"
