---
- name: Create Sickrage container
  docker_container:
    name: sickrage
    image: linuxserver/sickrage
    network_mode: host
    restart_policy: always
    state: started
    volumes:
       - /opt/sickrage:/config
       - /mnt/data/downloads/tv:/downloads
       - /mnt/data/tv:/tv
    exposed_ports:
      - 8081
    published_ports:
      - "8081:8081"
    env:
      TZ: America/Toronto # offset = -05:00 / DST -04:00
      PUID: 1000
      PGID: 1000
- include_tasks: copy.yml
