---
- pause:
    seconds: 10

- uri:
    url: "http://{{ uTower_user_user }}:{{ uTower_user_pass }}@{{ host_ip }}:{{ sickrage_port }}"
  register: login

- pushbullet:
    api_key: "{{ pushbullet_api }}"
    title: Sickrage web service is UP!
    device: Chrome
    body: "http://{{ host_ip }}:{{ sickrage_port }}"
