---
- name: Create htpc-manager container
  docker_container:
    name: htpcmanager
    image: linuxserver/htpcmanager
    network_mode: host
    restart_policy: always
    state: started
    pull: yes
    volumes:
       - /opt/htpcmanager:/config
    exposed_ports:
      - 8085
    published_ports:
      - "8085:8085"
    env:
      TZ: America/Toronto # offset = -05:00 / DST -04:00
      PUID: 1000
      PGID: 1000

- pause:
    seconds: 5

- uri:
    url: "http://{{ uTower_user_user }}:{{ uTower_user_pass }}@{{ host_ip }}:8085"
  register: login

- pushbullet:
    api_key: "{{ pushbullet_api }}"
    title: htpc-manager web service is UP!
    device: Chrome
    body: "http://{{ host_ip }}:8085"
