---
- pause:
    seconds: 8

- uri:
    url: "http://{{ uTower_user_user }}:{{ uTower_user_pass }}@{{ host_ip }}:{{ htpcmanager_port }}"
  register: login

- pushbullet:
    api_key: "{{ pushbullet_api }}"
    title: htpc-manager web service is UP!
    device: Chrome
    body: "http://{{ host_ip }}:{{ htpcmanager_port }}"
