---
- pause:
    seconds: 5

- uri:
    url: "http://{{ uTower_user_user }}:{{ uTower_user_pass }}@{{ host_ip }}:{{ duplicati_port }}"
  register: login

- pushbullet:
    api_key: "{{ pushbullet_api }}"
    title: Duplicati web service is UP!
    device: Chrome
    body: "http://{{ host_ip }}:{{ duplicati_port }}"
