---
- name: Set timezone
  file:
    state: link
    src: /usr/share/zoneinfo/{{ timesync_timezone }}
    dest: /etc/localtime
    force: yes
  notify: systemd-timesyncd configuration changed

- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
  notify: systemd-timesyncd configuration changed

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started
