# site.yml
---
- hosts: localhost
  become: yes

  roles:
    - role: uTower.mariadb
    - role: uTower.couchpotato
    - role: uTower.sickrage
    - role: uTower.kodi-headless
    - role: uTower.transmission
    - role: uTower.duplicati
    - role: uTower.htpcmanager
    - role: uTower.openvpnas
