# site.yml
---
- hosts: uTower.dev
  become: yes

  pre_tasks:

    # Copy custom/custom.yml.sample to host_vars/HOSTNAME.yml
    # Update variable values
    - name: Load custom variables from HOSTNAME.yml
      include_vars: 
        dir: host_vars
        name: 192.168.88.128
      failed_when: false

  roles:
    - role: uTower.mariadb