# site.yml
---
- hosts: kodi
  become: yes

  pre_tasks:

    # Copy custom/custom.yml.sample to custom/custom.yml
    # Update variable values
    - name: Load custom variables from custom.yml
      include_vars: group_vars/custom.yml
      failed_when: false

  roles:
#    - { role: uTower.base, when: ntp_enabled }
#    - { role: uTower.ntp, when: ntp_enabled }
#    - { role: uTower.kodi_client, when: kodi_client_enabled }

- hosts: uTower.dev
  become: yes

  pre_tasks:

    # Copy custom/custom.yml.sample to custom/custom.yml
    # Update variable values
#    - name: Load custom variables from custom.yml
#      include_vars: group_vars/uTower/uTower.yml
#      failed_when: false

  roles:
     - role: uTower.ntp
     - role: uTower.disk
     - role: uTower.mergerfs
     - role: uTower.common
     - role: uTower.nas
     - role: uTower.docker
     - role: uTower.snapraid

- hosts: uTower
  become: yes

  pre_tasks:

    # Copy custom/custom.yml.sample to custom/custom.yml
    # Update variable values
#    - name: Load custom variables from custom.yml
#      include_vars: group_vars/uTower/uTower.yml
#      failed_when: false

    - name: Load custom variables from custom.yml
      include_vars: group_vars/uTower/uTower.yml
      failed_when: false

  roles:
     - role: uTower.ntp
     - role: uTower.disk
     - role: uTower.mergerfs
     - role: uTower.common
     - role: uTower.nas
     - role: uTower.docker
     - role: uTower.snapraid
     
#     - role: uTower.kodi-headless
#     - role: uTower.mariadb
#     - role: uTower.transmission
#     - role: uTower.couchpotato
#     - role: uTower.sickrage

#    - { role: GR360RY.htpc-nas, when: htpc_nas_enabled }
#    - { role: GR360RY.docker, when: docker_enabled }
#    - { role: uTower.htpc-manager, when: htpc_manager_enabled }
#    - { role: uTower.transmission, when: transmission_enabled }
#    - { role: uTower.sickrage, when: sickrage_enabled }
#    - { role: uTower.couchpotato, when: couchpotato_enabled }
