---
- hosts: all
  become: yes

  roles:
    # Base
    - { role:  uTower.ntp, when: ntp_enabled }
    - { role:  uTower.disk, when: disk_enabled }
    - { role:  uTower.mergerfs, when: mergerfs_enabled }
    - { role:  uTower.common, when: common_enabled }
    - { role:  uTower.nas, when: nas_enabled }
    - { role:  uTower.snapraid, when: snapraid_enabled }
    - { role:  uTower.docker, when: docker_enabled }

    # Containers
    - { role:  uTower.mariadb, when: mariadb_enabled }
    - { role:  uTower.couchpotato, when: couchpotato_enabled }
    - { role:  uTower.sickrage, when: sickrage_enabled }
    - { role:  uTower.kodi-headless, when: kodiheadless_enabled }
    - { role:  uTower.transmission, when: transmission_enabled }
    - { role:  uTower.duplicati, when: duplicati_enabled }
    - { role:  uTower.htpcmanager, when: htpc_manager_enabled }
    - { role:  uTower.sonarr, when: sonarr_enabled }
    - { role:  uTower.radarr, when: radarr_enabled }
    - { role:  uTower.lidarr, when: lidarr_enabled }
    - { role:  uTower.madsonic, when: madsonic_enabled }