---
- name: Create Codiad container
  docker_container:
    name: codiad
    image: linuxserver/codiad
    network_mode: host
    restart_policy: always
    state: started
    volumes:
       - /opt/codiad:/config
       - /home/user:/projects
    exposed_ports:
      - 80:80
    published_ports:
      - "80:80"
    env:
      TZ: America/Toronto # offset = -05:00 / DST -04:00
      PUID: 1000
      PGID: 1000
#- include_tasks: copy.yml
