---
- name: List docker containers
  shell: "docker start {{ item }}"
  register: docker_containers
  args:
    executable: /bin/bash
  become: true
  with_items:
      - couchpotato
      - kodi-headless
      - mariadb
      - sickrage
      - transmission
      - htpcmanager

