---
docker_containers: []
# docker_containers:
#   - name: transmission
#   - name: transmission
#     image: linuxserver/transmission
#     published_ports: 9091:9091
#     env:

uTower_downloads: /downloads
uTower_downloads_incomplete: /downloads/incomplete

transmission_rpc_auth_required:
transmission_user: {{ uTower_user_user }}
transmission_pass: {{ uTower_user_pass }}

