---
- name: Create Media Folders
  file: path={{ item }} state=directory
  with_items:
    - /opt/kodi/.kodi/userdata/

- name: Copy advancedsettings.xml
  template: src=advancedsettings.xml.j2 dest=/opt/kodi/.kodi/userdata/advancedsettings.xml

- name: Copy advancedsettings.xml
  template: src=sources.xml.j2 dest=/opt/kodi/.kodi/userdata/sources.xml

- name: Create kodi-headless container
  docker_container:
    name: kodi-headless
    image: linuxserver/kodi-headless
    network_mode: host
    restart_policy: always
    state: started
    volumes:
       - /opt/kodi:/config
    exposed_ports:
      - 8777
    published_ports:
       - "8777:8080"
       - "9777:9777/udp"
    env:
      TZ: America/Toronto # offset = -05:00 / DST -04:00
      PUID: 1000
      PGID: 1000

- pause:
    seconds: 5

- uri:
    url: "http://{{ kodi_user }}:{{ kodi_pass }}@{{ host_ip }}:8080"
  register: login

- pushbullet:
    api_key: "{{ pushbullet_api }}"
    title: kodi-headless service is UP!
    device: Chrome
    body: "http://{{ host_ip }}:8080"
