---
- name: Create Media Folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ kodi_path }}.kodi/userdata/"

- name: Create advancedsettings.xml from template
  template: src=advancedsettings.xml.j2 dest="{{ kodi_path }}.kodi/userdata/advancedsettings.xml"

- name: Create sources.xml from template
  template: src=sources.xml.j2 dest="{{ kodi_path }}.kodi/userdata/sources.xml"

- name: Create kodi-headless container
  docker_container:
    name: kodi-headless
    image: linuxserver/kodi-headless
    network_mode: host
    pull: yes
    restart_policy: always
    state: started
    volumes:
       - /opt/kodi:/config
    exposed_ports:
      - 8777
      - 9777/udp
    published_ports:
       - "8080:8777"
       - "9777:9777/udp"
    env:
      TZ: America/Toronto # offset = -05:00 / DST -04:00
      PUID: 1000
      PGID: 1000

- include_tasks: pushbullet.yml
  when: pushbullet_enabled
