---
- pause:
    seconds: 10

- uri:
    url: "http://{{ kodi_user }}:{{ kodi_pass }}@{{ host_ip }}:{{ kodi_port }}"
  register: login

- pushbullet:
    api_key: "{{ pushbullet_api }}"
    title: kodi-headless service is UP!
    device: Chrome
    body: "http://{{ host_ip }}:{{ kodi_port }}"
