---
#|  Install and configure SnapRAID

- name: Adding SnapRAID PPA
  apt_repository:
    repo: ppa:tikhonov/snapraid
    state: present
    update_cache: yes

- name: Installing SnapRAID from PPA
  package:
    name: snapraid
    state: present
  when: snapraid_enabled | bool
  loop_control:
    loop_var: found_item
  tags: [ 'snapraid', 'snapraid-install' ]

- name: main - Configure SnapRAID
  include_vars:  '{{ found_item }}'
  with_first_found:
    - 'config/{{ ansible_distribution }}.yml'
    - 'config/{{ ansible_os_family }}.yml'
    - 'config/default.yml'
  when: snapraid_enabled | bool
  loop_control:
    loop_var: found_item
  tags: [ 'snapraid', 'snapraid-config' ]

- name: main - Configure crontab
  include_vars:  'cron.yml'
  when: snapraid_enabled | bool
  tags: [ 'snapraid', 'snapraid-cron' ]
