---
- template:
    src: create-mysql.sh.j2
    dest: /opt/mariadb/create-mysql.sh
    owner: user
    group: user
    mode: 0755

- shell: bash "{{ mariadb_path }}/create-mysql.sh"
  args:
    executable: /bin/bash
