---

- name: install/package-Ubuntu - Add PPA
  apt_repository:
    repo: '{{ snapraid_ppa }}'
    state: present

- name: install/package-Ubuntu - Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: install/package-Ubuntu - Install Snapraid
  apt: 
    name: '{{ snapraid_package_name }}'
    state: installed
