galaxy_info:
  author: Gregory Shulov
  description: An ansible role to perform common tasks on uTower
  license: BSD
  
  min_ansible_version: 2.0

  platforms:
    - name: Ubuntu
      versions:
      - trusty
  
  galaxy_tags:
    - uTower
    - system

dependencies: []
