---
dependencies: []

galaxy_info:
  author: "Chad Sheets"
  description: "Install and configure Snapraid from package or source"
  company: "LinConf"
  license: "MIT"
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - snapraid
    - system
