---
#| Set to `False` to disable the role
snapraid_enabled: True

# Set to False to build from source... and stop
snapraid_install: True

# Settings for /etc/snapraid.conf
snapraid_conf_parity_file:
  - '/mnt/parity/snapraid.parity'
snapraid_conf_content_list:
  - '/var/snapraid.content'
  - '/mnt/disk1/snapraid.content'
  - '/mnt/disk2/snapraid.content'
  - '/mnt/disk3/snapraid.content'
snapraid_conf_data_disk:
  - '/mnt/disk1/'
  - '/mnt/disk2/'
  - '/mnt/disk3/'
snapraid_conf_exclude:
  - '*.unrecoverable'
  - '/tmp/'
  - '/lost+found/'

# Settings for crontab
snapraid_cron_jobs: []
  # - name: Perform snapraid sync
  #   job: snapraid sync
  #   minute: 20
  #   hour: 2
  #   day: *
  #   weekday: *
  #   month: *
snapraid_cron_host_jobs: []
snapraid_cron_group_jobs: []

#|
#| Installation Options
#|

# Installs from package manager by default
snapraid_install_from_file: True
snapraid_install_from_source: False
snapraid_install_from_docker: False

#| Install from pre-compiled package file (example: files/Debian.deb)

snapraid_install_file_name: 'snapraid-v11.1.deb'

#| Build From Source

snapraid_build_git_repo: 'https://github.com/amadvance/snapraid.git'
snapraid_build_target_version: 'v11.1'
snapraid_build_user: '{{ ansible_ssh_user | default("root") }}'
snapraid_build_path: '/opt/snapraid/src'

snapraid_install_method: '{{ "source" if (snapraid_install_from_source | bool)
                              else "file" if (snapraid_install_from_file | bool)
                              else "docker" if (snapraid_install_from_docker | bool)
                              else "package" }}'
