---
  # tasks file for uTower.couchpotato
- name: Create couchpotato Folder
  file: path={{ item }} state=directory
  with_items:
    - "{{ couchpotato_path  }}"

- template:
    src: config.ini.j2
    dest: /opt/couchpotato/config.ini
    owner: user
    backup: yes

- name: Create CouchPotato container
  docker_container:
    name: couchpotato
    image: linuxserver/couchpotato
    network_mode: host
    restart_policy: always
    state: started
    pull: yes
    volumes:
       - /opt/couchpotato:/config
       - /mnt/data/downloads/movies:/downloads
       - /mnt/data/movies:/movies
    exposed_ports:
      - 5050
    published_ports:
      - "5050:5050"
    env:
      TZ: America/Toronto # offset = -05:00 / DST -04:00
      PUID: 1000
      PGID: 1000

- pause:
    seconds: 5

- uri:
    url: "http://{{ uTower_user_user }}:{{ uTower_user_pass }}@{{ host_ip }}:5050"
  register: login

- pushbullet:
    api_key: "{{ pushbullet_api }}"
    title: CouchPotato web service is UP!
    device: Chrome
    body: "http://{{ host_ip }}:5050"
