---
# tasks file for uTower.common

- name: Install pushbullet package
  pip: name=pushbullet.py state=present

# BLOCK: Configure SSH service
- block:

  - name: Make sure SSH server is installed for remote access
    apt: name=openssh-server state=installed update_cache=yes cache_valid_time=3600

  - name: Make sure SSH is started on boot
    service: name=ssh state=started enabled=yes

  tags: ssh
  when: uTower_ssh_service

# BLOCK: Create uTower group and user, enable sudo access
- block:

  - name: Create uTower group
    group: name={{ uTower_user_group }} state=present

  - name: Generate uTower user password
    command: /usr/bin/openssl passwd -salt random_salt -1 {{ uTower_user_pass }}
    register: uTower_user_generated_password
    changed_when: false

  - name: Create uTower user
    user:
      name={{ uTower_user_user }}
      password={{ uTower_user_generated_password.stdout }}
      group={{ uTower_user_group }}
      update_password=on_create
      state=present
      createhome=yes
      shell={{ uTower_user_shell }}
      groups=adm,cdrom,dip,plugdev
      append=yes
    register: uTower_user_verify_user

  - name: Set Fact "uTower_user_uid"
    set_fact: uTower_user_uid={{ uTower_user_verify_user.uid }}

  - name: Set Fact "uTower_user_gid"
    set_fact: uTower_user_gid={{ uTower_user_verify_user.group }}

  - name: Enable sudo for uTower user
    user:
      name={{ uTower_user_user }}
      groups=sudo
      append=yes
    when: uTower_user_sudo_access

  tags:
    - user

# Create media folders
- name: Create Media Folders
  file: path={{ item }} state=directory owner={{ uTower_user_user }} group={{ uTower_user_group }} mode=0755 recurse=yes
  with_items:
    - "{{ uTower_media_path }}/{{ uTower_media_movies }}"
    - "{{ uTower_media_path }}/{{ uTower_media_tv }}"
    - "{{ uTower_media_path }}/{{ uTower_media_music }}"
    - "{{ uTower_media_path }}/{{ uTower_media_pictures }}"
  when: uTower_create_media_folders
  tags:
    - media

- name: Create Downloads Folders
  file: path={{ item }} state=directory owner={{ uTower_user_user }} group={{ uTower_user_group }} mode=0755 recurse=yes
  with_items:
    - "{{ uTower_downloads_tv }}"
    - "{{ uTower_downloads_movies }}"
    - "{{ uTower_downloads_incomplete }}"

- name: Create Processing Folders
  file: path={{ item }} state=directory owner={{ uTower_user_user }} group={{ uTower_user_group }} mode=0755 recurse=yes
  with_items:
    - "{{ uTower_downloads_incomplete }}"

# BLOCK: Configure avahi and avahi alias
- block:

  - name: Install Avahi packages
    apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
    with_items:
      - avahi-daemon
      - libnss-mdns
      - python-avahi
      - python-pip
      - git
      - curl

  - name: Install avahi-aliases service
    pip: name='git+http://github.com/GR360RY/avahi-aliases' editable=false

  - name: Make sure avahi-aliases enabled and starts on boot
    service: name=avahi-daemon state=started enabled=yes

  tags: avahi
  when: uTower_zeroconf
