---
# tasks file for uTower.sonarr
- name: Create sonarr Folder
  file: path={{ item }} state=directory
  with_items:
    - "{{ sonarr_path  }}"

- name: Create sonarr container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    network_mode: host
    restart_policy: always
    state: started
    pull: yes
    volumes:
       - /opt/sonarr:/config
       - /mnt/data/downloads/tv:/downloads
       - /mnt/data/tv:/tv
    exposed_ports:
      - 8989
    published_ports:
      - "8989:8989"
    env:
      TZ: America/Toronto # offset = -05:00 / DST -04:00
      PUID: 1000
      PGID: 1000

- pause:
    seconds: 5

- uri:
    url: "http://{{ kodi_user }}:{{ kodi_pass }}@{{ host_ip }}:8989"
  register: login

- pushbullet:
    api_key: "{{ pushbullet_api }}"
    title: sonarr service is UP!
    device: Chrome
    body: "http://{{ host_ip }}:8989"
