---
- name: Create transmission Folder
  file: path={{ item }} state=directory
  with_items:
    - "{{ transmission_path }}"

- template:
    src: settings.json.j2
    dest: /opt/transmission/settings.json
    owner: user
    backup: no

- name: Wait until the file /settings.json is present before continuing
  wait_for:
    path: /opt/transmission/settings.json

- name: Create Transmission container
  docker_container:
    name: transmission
    image: linuxserver/transmission
    network_mode: host
    restart_policy: always
    state: started
    volumes:
       - /opt/transmission:/config
       - /mnt/data/downloads:/downloads
    exposed_ports:
      - 9091
      - 51413
    published_ports:
      - "9091:9091"
      - "51413:51413/udp"
    env:
      TZ: America/Toronto # offset = -05:00 / DST -04:00
      PUID: 1000
      PGID: 1000

- pause:
    seconds: 5

- uri:
    url: "http://{{ uTower_user_user }}:{{ uTower_user_pass }}@{{ host_ip }}:9091"
  register: login

- pushbullet:
    api_key: "{{ pushbullet_api }}"
    title: Transmission web service is UP!
    device: Chrome
    body: "{{ login.url }}"
