---
- name: mergerfs | install prereqs
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=600
  with_items:
    - fuse
    - xfsprogs

- name: download mergerfs release
  get_url:
    dest: /tmp/
    force: yes
    url: "https://github.com/trapexit/mergerfs/releases/download/{{ mergerfs_version }}/mergerfs_{{ mergerfs_version }}.ubuntu-xenial_amd64.deb"

- name: Install mergerfs
  apt: deb="/tmp/mergerfs_{{ mergerfs_version }}.ubuntu-xenial_amd64.deb"
  sudo: true

- include_tasks: mount.yml