---
- name: create /mnt point for mount_point
  file:
    dest: "{{ mount_point }}"
    state: directory
    mode: "0777"

- name: mount mergerfs array
  mount:
    name: "{{ mount_point }}"
    src: /mnt/disk*
<<<<<<< HEAD
    opts: defaults,allow_other,use_ino,minfreespace=1G,category.create=epmfs,fsname=mergerfs 0 0
=======
    opts: direct_io,defaults,allow_other,minfreespace=1G,fsname=mergerfs
>>>>>>> 5edfe67d6298977a370823c6d6f36545cf0e1a02
    fstype: fuse.mergerfs
    state: present

