---
- name: create /mnt point for mount_point
  file:
    dest: "{{ mount_point }}"
    state: directory
    mode: "0777"

- name: mount mergerfs array
  mount:
    name: "{{ mount_point }}"
    src: /mnt/disk*
    opts: direct_io,defaults,allow_other,minfreespace=1G,fsname=mergerfs
    fstype: fuse.mergerfs
    state: present

