---
- name: Create Jackett container
  docker_container:
    name: jackett
    image: linuxserver/jackett
    network_mode: host
    restart_policy: always
    state: started
    volumes:
       - /opt/jackett/:/config
    exposed_ports:
      - 9117
    published_ports:
      - "9117:9117"
    env:
      TZ: America/Toronto # offset = -05:00 / DST -04:00
      PUID: 1000
      PGID: 1000
